server:
  port: 8080

spring:
  application:
    name: xiaoyouxing
  datasource:
    url: jdbc:mysql://Localhost:3308/xiaoyouxing?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xiaoyou
    password: xiaoyou1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6380
  elasticsearch:
    rest:
      uris: http://localhost:9200
